Import("env")

LIBKOKI = "#lib/libkoki.so"

# All the example applications that don't need GL
for exname in [ "realtime_quads",
                "realtime_text",
                "marker_info" ]:
    env.Program( source = [ "{0}.c".format(exname),
                            LIBKOKI ],
                 target = exname )

# The GL example application
glenv = env.Clone()
glenv.ParseConfig( "pkg-config --cflags --libs gl glu" )
f = glenv.ParseFlags( "-lglut" )
glenv.MergeFlags(f)

glenv.Program( source = [ "realtime_gl.c",
                          LIBKOKI ],
               target = "realtime_gl" )

