Import("lk_env")

# All the example applications that don't need GL
for exname in [ "realtime_quads",
                "realtime_text",
                "marker_info",
                "html_log" ]:
    lk_env.Program( source = "{0}.c".format(exname),
                    target = exname )

# The GL example application
glenv = lk_env.Clone()
glenv.ParseConfig( "pkg-config --cflags --libs gl glu" )
f = glenv.ParseFlags( "-lglut" )
glenv.MergeFlags(f)

glenv.Program( source = "realtime_gl.c",
               target = "realtime_gl" )

