#!/bin/bash

if [ "$1" == "--help" ]
then
	echo "Usage:"
	echo ""
	echo "	./generate_authors [-e] filename"
	echo ""
	echo "Where the 'e' flag launches your EDITOR ($EDITOR) afterwards."
	exit 0
fi

FILENAME="AUTHORS"

if [ "$1" == "-e" ]
then
	FILENAME="$2"
else
	FILENAME="$1"
fi

echo "AUTHORS" > $FILENAME
echo "=======" >> $FILENAME
echo "" >> $FILENAME
echo "Listed in order of number of git commits, descending:" >> $FILENAME
echo "" >> $FILENAME

git log --format='%aN <%aE>' |
	awk '{arr[$0]++} END{for (i in arr){print arr[i], i;}}' |
	sort -rn |
	cut -d\  -f2- |
	awk '{printf("   %s\n", $0);}' >> $FILENAME

echo "" >> $FILENAME

if [ "$1" == "-e" ]
then
	$EDITOR $FILENAME
fi

echo "Done."
exit 0