Import("env install dest")

c_files = Glob( "*.c" )

lib = env.SharedLibrary( "#lib/libkoki", c_files )

install += [ env.Install( dir = dest( "/usr/lib" ),
                          source = lib ) ]
