Import("env install dest")

c_files = Glob( "*.c" )

lib = env.SharedLibrary( "#lib/libkoki", c_files )

install += [ env.Install( dir = dest( "/lib" ),
                          source = lib ) ]

# Also install the library with a version
install += [ env.InstallAs( target = dest( "/lib/libkoki.so.0.0" ),
                            source = lib ) ]
